use_frameworks!

platform :ios, '9.0'

target 'IGUniversalComponents_Example' do
  pod 'IGUniversalComponents', :path => '../'

  target 'IGUniversalComponents_Tests' do
    inherit! :search_paths

    
  end
end
